/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicRecrutementRouteImport } from './routes/_public.recrutement'
import { Route as PublicProfessionnelsRouteImport } from './routes/_public.professionnels'
import { Route as PublicPolitiqueConfidentialiteRouteImport } from './routes/_public.politique-confidentialite'
import { Route as PublicParticuliersRouteImport } from './routes/_public.particuliers'
import { Route as PublicMentionsLegalesRouteImport } from './routes/_public.mentions-legales'
import { Route as PublicCookiesRouteImport } from './routes/_public.cookies'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicAProposRouteImport } from './routes/_public.a-propos'
import { Route as PublicProfessionnelsIndexRouteImport } from './routes/_public.professionnels.index'
import { Route as PublicParticuliersIndexRouteImport } from './routes/_public.particuliers.index'
import { Route as PublicParticuliersSlugRouteImport } from './routes/_public.particuliers.$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRecrutementRoute = PublicRecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProfessionnelsRoute = PublicProfessionnelsRouteImport.update({
  id: '/professionnels',
  path: '/professionnels',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPolitiqueConfidentialiteRoute =
  PublicPolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicParticuliersRoute = PublicParticuliersRouteImport.update({
  id: '/particuliers',
  path: '/particuliers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMentionsLegalesRoute = PublicMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCookiesRoute = PublicCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAProposRoute = PublicAProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProfessionnelsIndexRoute =
  PublicProfessionnelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicProfessionnelsRoute,
  } as any)
const PublicParticuliersIndexRoute = PublicParticuliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicParticuliersRoute,
} as any)
const PublicParticuliersSlugRoute = PublicParticuliersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicParticuliersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/a-propos': typeof PublicAProposRoute
  '/contact': typeof PublicContactRoute
  '/cookies': typeof PublicCookiesRoute
  '/mentions-legales': typeof PublicMentionsLegalesRoute
  '/particuliers': typeof PublicParticuliersRouteWithChildren
  '/politique-confidentialite': typeof PublicPolitiqueConfidentialiteRoute
  '/professionnels': typeof PublicProfessionnelsRouteWithChildren
  '/recrutement': typeof PublicRecrutementRoute
  '/particuliers/$slug': typeof PublicParticuliersSlugRoute
  '/particuliers/': typeof PublicParticuliersIndexRoute
  '/professionnels/': typeof PublicProfessionnelsIndexRoute
}
export interface FileRoutesByTo {
  '/a-propos': typeof PublicAProposRoute
  '/contact': typeof PublicContactRoute
  '/cookies': typeof PublicCookiesRoute
  '/mentions-legales': typeof PublicMentionsLegalesRoute
  '/politique-confidentialite': typeof PublicPolitiqueConfidentialiteRoute
  '/recrutement': typeof PublicRecrutementRoute
  '/': typeof PublicIndexRoute
  '/particuliers/$slug': typeof PublicParticuliersSlugRoute
  '/particuliers': typeof PublicParticuliersIndexRoute
  '/professionnels': typeof PublicProfessionnelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/a-propos': typeof PublicAProposRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/cookies': typeof PublicCookiesRoute
  '/_public/mentions-legales': typeof PublicMentionsLegalesRoute
  '/_public/particuliers': typeof PublicParticuliersRouteWithChildren
  '/_public/politique-confidentialite': typeof PublicPolitiqueConfidentialiteRoute
  '/_public/professionnels': typeof PublicProfessionnelsRouteWithChildren
  '/_public/recrutement': typeof PublicRecrutementRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/particuliers/$slug': typeof PublicParticuliersSlugRoute
  '/_public/particuliers/': typeof PublicParticuliersIndexRoute
  '/_public/professionnels/': typeof PublicProfessionnelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/cookies'
    | '/mentions-legales'
    | '/particuliers'
    | '/politique-confidentialite'
    | '/professionnels'
    | '/recrutement'
    | '/particuliers/$slug'
    | '/particuliers/'
    | '/professionnels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/a-propos'
    | '/contact'
    | '/cookies'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/recrutement'
    | '/'
    | '/particuliers/$slug'
    | '/particuliers'
    | '/professionnels'
  id:
    | '__root__'
    | '/_public'
    | '/_public/a-propos'
    | '/_public/contact'
    | '/_public/cookies'
    | '/_public/mentions-legales'
    | '/_public/particuliers'
    | '/_public/politique-confidentialite'
    | '/_public/professionnels'
    | '/_public/recrutement'
    | '/_public/'
    | '/_public/particuliers/$slug'
    | '/_public/particuliers/'
    | '/_public/professionnels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/recrutement': {
      id: '/_public/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof PublicRecrutementRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/professionnels': {
      id: '/_public/professionnels'
      path: '/professionnels'
      fullPath: '/professionnels'
      preLoaderRoute: typeof PublicProfessionnelsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/politique-confidentialite': {
      id: '/_public/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PublicPolitiqueConfidentialiteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/particuliers': {
      id: '/_public/particuliers'
      path: '/particuliers'
      fullPath: '/particuliers'
      preLoaderRoute: typeof PublicParticuliersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mentions-legales': {
      id: '/_public/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof PublicMentionsLegalesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cookies': {
      id: '/_public/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof PublicCookiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/a-propos': {
      id: '/_public/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof PublicAProposRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/professionnels/': {
      id: '/_public/professionnels/'
      path: '/'
      fullPath: '/professionnels/'
      preLoaderRoute: typeof PublicProfessionnelsIndexRouteImport
      parentRoute: typeof PublicProfessionnelsRoute
    }
    '/_public/particuliers/': {
      id: '/_public/particuliers/'
      path: '/'
      fullPath: '/particuliers/'
      preLoaderRoute: typeof PublicParticuliersIndexRouteImport
      parentRoute: typeof PublicParticuliersRoute
    }
    '/_public/particuliers/$slug': {
      id: '/_public/particuliers/$slug'
      path: '/$slug'
      fullPath: '/particuliers/$slug'
      preLoaderRoute: typeof PublicParticuliersSlugRouteImport
      parentRoute: typeof PublicParticuliersRoute
    }
  }
}

interface PublicParticuliersRouteChildren {
  PublicParticuliersSlugRoute: typeof PublicParticuliersSlugRoute
  PublicParticuliersIndexRoute: typeof PublicParticuliersIndexRoute
}

const PublicParticuliersRouteChildren: PublicParticuliersRouteChildren = {
  PublicParticuliersSlugRoute: PublicParticuliersSlugRoute,
  PublicParticuliersIndexRoute: PublicParticuliersIndexRoute,
}

const PublicParticuliersRouteWithChildren =
  PublicParticuliersRoute._addFileChildren(PublicParticuliersRouteChildren)

interface PublicProfessionnelsRouteChildren {
  PublicProfessionnelsIndexRoute: typeof PublicProfessionnelsIndexRoute
}

const PublicProfessionnelsRouteChildren: PublicProfessionnelsRouteChildren = {
  PublicProfessionnelsIndexRoute: PublicProfessionnelsIndexRoute,
}

const PublicProfessionnelsRouteWithChildren =
  PublicProfessionnelsRoute._addFileChildren(PublicProfessionnelsRouteChildren)

interface PublicRouteChildren {
  PublicAProposRoute: typeof PublicAProposRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicCookiesRoute: typeof PublicCookiesRoute
  PublicMentionsLegalesRoute: typeof PublicMentionsLegalesRoute
  PublicParticuliersRoute: typeof PublicParticuliersRouteWithChildren
  PublicPolitiqueConfidentialiteRoute: typeof PublicPolitiqueConfidentialiteRoute
  PublicProfessionnelsRoute: typeof PublicProfessionnelsRouteWithChildren
  PublicRecrutementRoute: typeof PublicRecrutementRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAProposRoute: PublicAProposRoute,
  PublicContactRoute: PublicContactRoute,
  PublicCookiesRoute: PublicCookiesRoute,
  PublicMentionsLegalesRoute: PublicMentionsLegalesRoute,
  PublicParticuliersRoute: PublicParticuliersRouteWithChildren,
  PublicPolitiqueConfidentialiteRoute: PublicPolitiqueConfidentialiteRoute,
  PublicProfessionnelsRoute: PublicProfessionnelsRouteWithChildren,
  PublicRecrutementRoute: PublicRecrutementRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
