/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeadgenerationRouteImport } from './routes/leadgeneration'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as LeadgenerationIndexRouteImport } from './routes/leadgeneration.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as LeadgenerationLoginRouteImport } from './routes/leadgeneration.login'
import { Route as PublicRecrutementRouteImport } from './routes/_public.recrutement'
import { Route as PublicProfessionnelsRouteImport } from './routes/_public.professionnels'
import { Route as PublicPolitiqueDeConfidentialiteRouteImport } from './routes/_public.politique-de-confidentialite'
import { Route as PublicParticuliersRouteImport } from './routes/_public.particuliers'
import { Route as PublicMentionsLegalesRouteImport } from './routes/_public.mentions-legales'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicConditionsGeneralesRouteImport } from './routes/_public.conditions-generales'
import { Route as PublicAProposRouteImport } from './routes/_public.a-propos'
import { Route as PublicProfessionnelsIndexRouteImport } from './routes/_public.professionnels.index'
import { Route as PublicParticuliersIndexRouteImport } from './routes/_public.particuliers.index'
import { Route as PublicProfessionnelsSlugRouteImport } from './routes/_public.professionnels.$slug'
import { Route as PublicParticuliersSlugRouteImport } from './routes/_public.particuliers.$slug'

const LeadgenerationRoute = LeadgenerationRouteImport.update({
  id: '/leadgeneration',
  path: '/leadgeneration',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadgenerationIndexRoute = LeadgenerationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadgenerationRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const LeadgenerationLoginRoute = LeadgenerationLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LeadgenerationRoute,
} as any)
const PublicRecrutementRoute = PublicRecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProfessionnelsRoute = PublicProfessionnelsRouteImport.update({
  id: '/professionnels',
  path: '/professionnels',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPolitiqueDeConfidentialiteRoute =
  PublicPolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicParticuliersRoute = PublicParticuliersRouteImport.update({
  id: '/particuliers',
  path: '/particuliers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMentionsLegalesRoute = PublicMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConditionsGeneralesRoute =
  PublicConditionsGeneralesRouteImport.update({
    id: '/conditions-generales',
    path: '/conditions-generales',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAProposRoute = PublicAProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProfessionnelsIndexRoute =
  PublicProfessionnelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicProfessionnelsRoute,
  } as any)
const PublicParticuliersIndexRoute = PublicParticuliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicParticuliersRoute,
} as any)
const PublicProfessionnelsSlugRoute =
  PublicProfessionnelsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PublicProfessionnelsRoute,
  } as any)
const PublicParticuliersSlugRoute = PublicParticuliersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicParticuliersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/leadgeneration': typeof LeadgenerationRouteWithChildren
  '/a-propos': typeof PublicAProposRoute
  '/conditions-generales': typeof PublicConditionsGeneralesRoute
  '/contact': typeof PublicContactRoute
  '/mentions-legales': typeof PublicMentionsLegalesRoute
  '/particuliers': typeof PublicParticuliersRouteWithChildren
  '/politique-de-confidentialite': typeof PublicPolitiqueDeConfidentialiteRoute
  '/professionnels': typeof PublicProfessionnelsRouteWithChildren
  '/recrutement': typeof PublicRecrutementRoute
  '/leadgeneration/login': typeof LeadgenerationLoginRoute
  '/leadgeneration/': typeof LeadgenerationIndexRoute
  '/particuliers/$slug': typeof PublicParticuliersSlugRoute
  '/professionnels/$slug': typeof PublicProfessionnelsSlugRoute
  '/particuliers/': typeof PublicParticuliersIndexRoute
  '/professionnels/': typeof PublicProfessionnelsIndexRoute
}
export interface FileRoutesByTo {
  '/a-propos': typeof PublicAProposRoute
  '/conditions-generales': typeof PublicConditionsGeneralesRoute
  '/contact': typeof PublicContactRoute
  '/mentions-legales': typeof PublicMentionsLegalesRoute
  '/politique-de-confidentialite': typeof PublicPolitiqueDeConfidentialiteRoute
  '/recrutement': typeof PublicRecrutementRoute
  '/leadgeneration/login': typeof LeadgenerationLoginRoute
  '/': typeof PublicIndexRoute
  '/leadgeneration': typeof LeadgenerationIndexRoute
  '/particuliers/$slug': typeof PublicParticuliersSlugRoute
  '/professionnels/$slug': typeof PublicProfessionnelsSlugRoute
  '/particuliers': typeof PublicParticuliersIndexRoute
  '/professionnels': typeof PublicProfessionnelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/leadgeneration': typeof LeadgenerationRouteWithChildren
  '/_public/a-propos': typeof PublicAProposRoute
  '/_public/conditions-generales': typeof PublicConditionsGeneralesRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/mentions-legales': typeof PublicMentionsLegalesRoute
  '/_public/particuliers': typeof PublicParticuliersRouteWithChildren
  '/_public/politique-de-confidentialite': typeof PublicPolitiqueDeConfidentialiteRoute
  '/_public/professionnels': typeof PublicProfessionnelsRouteWithChildren
  '/_public/recrutement': typeof PublicRecrutementRoute
  '/leadgeneration/login': typeof LeadgenerationLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/leadgeneration/': typeof LeadgenerationIndexRoute
  '/_public/particuliers/$slug': typeof PublicParticuliersSlugRoute
  '/_public/professionnels/$slug': typeof PublicProfessionnelsSlugRoute
  '/_public/particuliers/': typeof PublicParticuliersIndexRoute
  '/_public/professionnels/': typeof PublicProfessionnelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leadgeneration'
    | '/a-propos'
    | '/conditions-generales'
    | '/contact'
    | '/mentions-legales'
    | '/particuliers'
    | '/politique-de-confidentialite'
    | '/professionnels'
    | '/recrutement'
    | '/leadgeneration/login'
    | '/leadgeneration/'
    | '/particuliers/$slug'
    | '/professionnels/$slug'
    | '/particuliers/'
    | '/professionnels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/a-propos'
    | '/conditions-generales'
    | '/contact'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/recrutement'
    | '/leadgeneration/login'
    | '/'
    | '/leadgeneration'
    | '/particuliers/$slug'
    | '/professionnels/$slug'
    | '/particuliers'
    | '/professionnels'
  id:
    | '__root__'
    | '/_public'
    | '/leadgeneration'
    | '/_public/a-propos'
    | '/_public/conditions-generales'
    | '/_public/contact'
    | '/_public/mentions-legales'
    | '/_public/particuliers'
    | '/_public/politique-de-confidentialite'
    | '/_public/professionnels'
    | '/_public/recrutement'
    | '/leadgeneration/login'
    | '/_public/'
    | '/leadgeneration/'
    | '/_public/particuliers/$slug'
    | '/_public/professionnels/$slug'
    | '/_public/particuliers/'
    | '/_public/professionnels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  LeadgenerationRoute: typeof LeadgenerationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leadgeneration': {
      id: '/leadgeneration'
      path: '/leadgeneration'
      fullPath: '/leadgeneration'
      preLoaderRoute: typeof LeadgenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadgeneration/': {
      id: '/leadgeneration/'
      path: '/'
      fullPath: '/leadgeneration/'
      preLoaderRoute: typeof LeadgenerationIndexRouteImport
      parentRoute: typeof LeadgenerationRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/leadgeneration/login': {
      id: '/leadgeneration/login'
      path: '/login'
      fullPath: '/leadgeneration/login'
      preLoaderRoute: typeof LeadgenerationLoginRouteImport
      parentRoute: typeof LeadgenerationRoute
    }
    '/_public/recrutement': {
      id: '/_public/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof PublicRecrutementRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/professionnels': {
      id: '/_public/professionnels'
      path: '/professionnels'
      fullPath: '/professionnels'
      preLoaderRoute: typeof PublicProfessionnelsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/politique-de-confidentialite': {
      id: '/_public/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PublicPolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/particuliers': {
      id: '/_public/particuliers'
      path: '/particuliers'
      fullPath: '/particuliers'
      preLoaderRoute: typeof PublicParticuliersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mentions-legales': {
      id: '/_public/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof PublicMentionsLegalesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/conditions-generales': {
      id: '/_public/conditions-generales'
      path: '/conditions-generales'
      fullPath: '/conditions-generales'
      preLoaderRoute: typeof PublicConditionsGeneralesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/a-propos': {
      id: '/_public/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof PublicAProposRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/professionnels/': {
      id: '/_public/professionnels/'
      path: '/'
      fullPath: '/professionnels/'
      preLoaderRoute: typeof PublicProfessionnelsIndexRouteImport
      parentRoute: typeof PublicProfessionnelsRoute
    }
    '/_public/particuliers/': {
      id: '/_public/particuliers/'
      path: '/'
      fullPath: '/particuliers/'
      preLoaderRoute: typeof PublicParticuliersIndexRouteImport
      parentRoute: typeof PublicParticuliersRoute
    }
    '/_public/professionnels/$slug': {
      id: '/_public/professionnels/$slug'
      path: '/$slug'
      fullPath: '/professionnels/$slug'
      preLoaderRoute: typeof PublicProfessionnelsSlugRouteImport
      parentRoute: typeof PublicProfessionnelsRoute
    }
    '/_public/particuliers/$slug': {
      id: '/_public/particuliers/$slug'
      path: '/$slug'
      fullPath: '/particuliers/$slug'
      preLoaderRoute: typeof PublicParticuliersSlugRouteImport
      parentRoute: typeof PublicParticuliersRoute
    }
  }
}

interface PublicParticuliersRouteChildren {
  PublicParticuliersSlugRoute: typeof PublicParticuliersSlugRoute
  PublicParticuliersIndexRoute: typeof PublicParticuliersIndexRoute
}

const PublicParticuliersRouteChildren: PublicParticuliersRouteChildren = {
  PublicParticuliersSlugRoute: PublicParticuliersSlugRoute,
  PublicParticuliersIndexRoute: PublicParticuliersIndexRoute,
}

const PublicParticuliersRouteWithChildren =
  PublicParticuliersRoute._addFileChildren(PublicParticuliersRouteChildren)

interface PublicProfessionnelsRouteChildren {
  PublicProfessionnelsSlugRoute: typeof PublicProfessionnelsSlugRoute
  PublicProfessionnelsIndexRoute: typeof PublicProfessionnelsIndexRoute
}

const PublicProfessionnelsRouteChildren: PublicProfessionnelsRouteChildren = {
  PublicProfessionnelsSlugRoute: PublicProfessionnelsSlugRoute,
  PublicProfessionnelsIndexRoute: PublicProfessionnelsIndexRoute,
}

const PublicProfessionnelsRouteWithChildren =
  PublicProfessionnelsRoute._addFileChildren(PublicProfessionnelsRouteChildren)

interface PublicRouteChildren {
  PublicAProposRoute: typeof PublicAProposRoute
  PublicConditionsGeneralesRoute: typeof PublicConditionsGeneralesRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicMentionsLegalesRoute: typeof PublicMentionsLegalesRoute
  PublicParticuliersRoute: typeof PublicParticuliersRouteWithChildren
  PublicPolitiqueDeConfidentialiteRoute: typeof PublicPolitiqueDeConfidentialiteRoute
  PublicProfessionnelsRoute: typeof PublicProfessionnelsRouteWithChildren
  PublicRecrutementRoute: typeof PublicRecrutementRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAProposRoute: PublicAProposRoute,
  PublicConditionsGeneralesRoute: PublicConditionsGeneralesRoute,
  PublicContactRoute: PublicContactRoute,
  PublicMentionsLegalesRoute: PublicMentionsLegalesRoute,
  PublicParticuliersRoute: PublicParticuliersRouteWithChildren,
  PublicPolitiqueDeConfidentialiteRoute: PublicPolitiqueDeConfidentialiteRoute,
  PublicProfessionnelsRoute: PublicProfessionnelsRouteWithChildren,
  PublicRecrutementRoute: PublicRecrutementRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface LeadgenerationRouteChildren {
  LeadgenerationLoginRoute: typeof LeadgenerationLoginRoute
  LeadgenerationIndexRoute: typeof LeadgenerationIndexRoute
}

const LeadgenerationRouteChildren: LeadgenerationRouteChildren = {
  LeadgenerationLoginRoute: LeadgenerationLoginRoute,
  LeadgenerationIndexRoute: LeadgenerationIndexRoute,
}

const LeadgenerationRouteWithChildren = LeadgenerationRoute._addFileChildren(
  LeadgenerationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  LeadgenerationRoute: LeadgenerationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
